"""Add database indexes

Revision ID: 2f07f3609a6b
Revises: 
Create Date: 2026-08-09 03:18:39.492807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f07f3609a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_renter_id'), ['renter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_status'), ['status'], unique=False)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_renter_id'), ['renter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('featured_room_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_featured_room_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_featured_room_request_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_featured_room_request_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_featured_room_request_status'), ['status'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('premium_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premium_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_request_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_approved'), ['approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('wallet_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_wallet_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_created_at'))

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_user_id'))
        batch_op.create_unique_constraint(batch_op.f('wallet_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_owner_id'))
        batch_op.drop_index(batch_op.f('ix_room_featured'))
        batch_op.drop_index(batch_op.f('ix_room_city'))
        batch_op.drop_index(batch_op.f('ix_room_approved'))

    with op.batch_alter_table('premium_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premium_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_premium_request_status'))
        batch_op.drop_index(batch_op.f('ix_premium_request_created_at'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_room_id'))
        batch_op.drop_index(batch_op.f('ix_message_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    with op.batch_alter_table('featured_room_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_featured_room_request_status'))
        batch_op.drop_index(batch_op.f('ix_featured_room_request_room_id'))
        batch_op.drop_index(batch_op.f('ix_featured_room_request_owner_id'))
        batch_op.drop_index(batch_op.f('ix_featured_room_request_created_at'))

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_room_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_renter_id'))

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status'))
        batch_op.drop_index(batch_op.f('ix_application_room_id'))
        batch_op.drop_index(batch_op.f('ix_application_renter_id'))

    # ### end Alembic commands ###
